.Dd May 14, 2017
.Dt PATHS 1
.Os Darwin
.Sh NAME
.Nm paths
.Nd Find file system paths in input
.Sh SYNOPSIS
.Nm
.Op Fl avh
.Sh DESCRIPTION
.Nm
is a command line tool which finds file system paths in standard
input and prints it to standard output.
.Pp
The following flags are supported:
.Bl -tag -width -indent
.It Fl a, -absolute-only
Do not resolve and include relative paths
.It Fl v, -version
Print program version and exit
.It Fl h, -help
Print help and exit
.El
.Sh SEE ALSO
.Xr copy 1 ,
.Xr show 1 ,
.Xr snap 1 
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjornt@gmail.com>
