.Dd May 14, 2017
.Dt SHOW 1
.Os Darwin
.Sh NAME
.Nm show
.Nd Show one or more files in the Mac OS X Finder
.Sh SYNOPSIS
.Nm
.Op Fl nvh
.Op Ar
.Sh DESCRIPTION
.Nm
is a command line tool which shows file arguments in the Mac
OS X Finder.
.Pp
The following flags are supported:
.Bl -tag -width -indent
.It Fl n, -new
Open new file viewer when showing file(s)
.It Fl v, -version
Print program version and exit
.It Fl h, -help
Print help and exit
.El
.Sh SEE ALSO
.Xr snap 1 ,
.Xr copy 1
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjornt@gmail.com>
