.Dd Jun 5, 2017
.Dt COMMENT 1
.Os Darwin
.Sh NAME
.Nm comment
.Nd Add a Finder comment to one or more files
.Sh SYNOPSIS
.Nm
.Op Fl vhf
.Op Ar
.Sh DESCRIPTION
.Nm
is a command line tool which sets the macOS Finder comment for
one or more files. The Finder must be running when the tool is run.
.Pp
The following flags are supported:
.Bl -tag -width -indent
Ignore file limit. This flag is required to run the tool on
a large number of files.
.It Fl v, -version
Print program version and exit
.It Fl h, -help
Print help and exit
.El
.Sh SEE ALSO
.Xr copy 1 ,
.Xr getinfo 1 ,
.Xr open 1 ,
.Xr paths 1 ,
.Xr show 1 ,
.Xr snap 1 ,
.Xr trash 1
.Sh AUTHORS
.An Sveinbjorn Thordarson <sveinbjornt@gmail.com>
